spring:
  datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  h2: #메모리 모드로 쓸경우 추가
    console: #메모리 모드로 쓸경우 추가
      enabled: true           #메모리 모드로 쓸경우 추가


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter